# Generated by Django 3.2.13 on 2022-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sur_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('adhaar', models.ImageField(upload_to='')),
                ('address1', models.CharField(default='', max_length=50)),
                ('address2', models.CharField(default='', max_length=50)),
                ('Courses', models.CharField(default='', max_length=50)),
                ('total_fees', models.IntegerField(default=0)),
                ('deposited_fees', models.IntegerField(default=0)),
                ('pending_fees', models.IntegerField(default=0)),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
