# Generated by Django 3.2.13 on 2022-07-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pending_fees',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
