# Generated by Django 3.2.13 on 2022-07-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_alter_student_pending_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pid',
            field=models.UUIDField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
